name: BEP032-tutorials
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - matplotlib
  - pandas
  - scipy
  - singularity
  - spython
  - pip
  - pip:
    - probeinterface
    - spikeinterface>=0.95.0
    - memory_profiler
    - sklearn
    - networkx
    - neo
    - nixio
    # - sphinx
    # - nbsphinx
    # - sphinx_gallery
    # - myst_parser